config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'
  mount ActionCable.server => "/cable"
  get 'chat_rooms/show'
  get 'products/search', to: 'products#search'
  devise_for :users
  root to: 'products#index'
    resources :products do
      resources :pictures, only: [:new, :create, :destroy]
      resources :sales, only: [:create, :destroy] do
        resources :reviews, only: [:create, :new, :destroy]
      end
    end
  resources :users, except: [:destroy, :create, :new]
  get 'dashboard', to: 'users#dashboard'
  resources :payments, only: [:new, :create]
  get 'payments/confirm', to: 'payments#confirm'
  get 'payments/retrieve', to: 'payments#retrieve'
  get 'payments/moneyback', to: 'payments#moneyback'
  resources :chat_rooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
   #these are handled by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :subscribed_user, :foreign_key => :subscribed_user_id, class_name: 'User'
  belongs_to :product

  validates :user_id, :subscribed_user_id, :product_id, :notification_type, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def link_through
    @notification = Notification.find(params[:id])
    @notification.update read: true
    if @notification.notification_type == "sale"
      redirect_to product_path(@notification.product)
    elsif @notification.notification_type == "message"
      redirect_to chat_room_path(@notification.product)
    elsif @notification.notification_type == "expired"
      redirect_to edit_product_path(@notification.product)
    else @notification.notification_type == "finish"
      redirect_to new_product_sale_review_path(@notification.product, @notification.product.sale)
    end
    authorize @notification
  end
end

app/views/notifications/_notification_dropdown.html.erb
<div class="navbar-wagon-item">
  <div class="dropdown navbar-wagon-link navbar-wagon-item ">
    <% if current_user.notifications.where(read: false).any? %>
      <div class="dropdown-toggle notification-present" id= 'dropdownMenu1' data-toggle='dropdown' aria-haspopup= true, aria-expanded=true >
        <i class="fas fa-globe"></i>
        <%= current_user.notifications.where(read: false).count %>
      </div>
    <% else %>
      <div class="dropdown-toggle" id= 'dropdownMenu1' data-toggle='dropdown' aria-haspopup= true, aria-expanded=true >
        <i class="fas fa-globe"></i>
        <%= current_user.notifications.where(read: false).count %>
      </div>
    <% end %>
    <ul class="dropdown-menu notif-dropdown" aria-labelledby='dropdownMenu1'>
      <li class="dropdown-header text-center">Notifications</li>
        <% current_user.notifications.each do |notification| %>
        <% unless notification.read? %>
          <li>
            <% notification_sender = User.find(notification.subscribed_user_id) %>
            <% if notification.notification_type == "message" %>
              <%= link_to "#{notification_sender.first_name} sent you a message", link_through_path(notification) %>
            <% elsif notification.notification_type == "sale" %>
              <%= link_to "#{notification_sender.first_name} bought one of your products", link_through_path(notification) %>
            <% elsif notification.notification_type == "expired"  %>
              <%= link_to "#{notification.product.name} expired, modify its pickup time", link_through_path(notification) %>
            <% else%>
              <%= link_to "Have you picked up #{notification.product.name} from #{notification_sender.first_name}? Please review this transaction", link_through_path(notification) %>
            <% end %>
          </li>
          <% end %>
        <% end %>
    </ul>
  </div>
</div>