config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'
  mount ActionCable.server => "/cable"
  get 'chat_rooms/show'
  get 'products/search', to: 'products#search'
  devise_for :users
  root to: 'products#index'
    resources :products do
      resources :pictures, only: [:new, :create, :destroy]
      resources :sales, only: [:create, :destroy] do
        resources :reviews, only: [:create, :new, :destroy]
      end
    end
  resources :users, except: [:destroy, :create, :new]
  get 'dashboard', to: 'users#dashboard'
  resources :payments, only: [:new, :create]
  get 'payments/confirm', to: 'payments#confirm'
  get 'payments/retrieve', to: 'payments#retrieve'
  get 'payments/moneyback', to: 'payments#moneyback'
  resources :chat_rooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
   #these are handled by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class = 'footer'>
  <div class = 'column-footer'>
    <p>Options</p>
    <% if user_signed_in? %>
      <%= link_to "Add Product", new_product_path, class:"column-footer-details" %>
      <%= link_to "My Dashboard", dashboard_path, class:"column-footer-details"%>
      <%= link_to "My Profile Page", user_path(current_user), class:"column-footer-details" %>
      <%= link_to "Sign Out", destroy_user_session_path, class:"column-footer-details" %>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "column-footer-details" %>
    <% end %>
  </div>

  <div class = 'column-footer'>
    <p>Check out our social media</p>
    <div class = 'column-footer-social'>
      <i class="fab fa-twitter-square"></i>
      <i class="fab fa-facebook-square"></i>
      <i class="fab fa-instagram"></i>
      <i class="fab fa-linkedin"></i>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    Quick Sell
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <%= form_tag(products_search_path, method: "get") do %>
      <%= text_field_tag :query,
          params[:query],
          placeholder: "Find a product"
        %>
    <% end %>

    <% if user_signed_in? %>


      <!-- Links when logged in -->
      <%= link_to "Add a product", new_product_path, class: "navbar-wagon-item navbar-wagon-link"  %>
      <%= render 'notifications/notification_dropdown' %>

      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div alt="" class="navbar-wagon-link navbar-wagon-item" data-toggle="dropdown"> <%= current_user.wallet %> € </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to 'Add Money', new_payment_path %>
            </li>
            <li>
              <%= link_to 'Withdraw Money', payments_retrieve_path %>
            </li>
          </ul>
        </div>
      </div>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.profile_picture? %>
            <img src="<%=  cl_image_path (current_user.profile_picture), :gravity=>'faces' %>" alt="" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% else %>
            <div class="dropdown-toggle navbar-wagon-link navbar-wagon-item" id="navbar-wagon-menu" data-toggle="dropdown"> <%= current_user.first_name %> </div>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fas fa-tachometer-alt"></i>  <%= t(".dashboard", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to chat_rooms_path do %>
                <i class="fas fa-envelope"></i>  <%= t(".chat_rooms", default: "Messages") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <% if user_signed_in? %>
       <%= render 'notifications/notification_dropdown' %>
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li> <%= link_to "Dashboard", dashboard_path %></li>
          <li> <%= link_to "My Profile", user_path(current_user) %></li>
          <li> <%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <li> <%= link_to "Add a product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li> <%= link_to "Add money", new_payment_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li> <%= link_to "Withdraw money", payments_retrieve_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        </ul>
      <% else %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>
  </div>
</div>