config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'
  mount ActionCable.server => "/cable"
  get 'chat_rooms/show'
  get 'products/search', to: 'products#search'
  devise_for :users
  root to: 'products#index'
    resources :products do
      resources :pictures, only: [:new, :create, :destroy]
      resources :sales, only: [:create, :destroy] do
        resources :reviews, only: [:create, :new, :destroy]
      end
    end
  resources :users, except: [:destroy, :create, :new]
  get 'dashboard', to: 'users#dashboard'
  resources :payments, only: [:new, :create]
  get 'payments/confirm', to: 'payments#confirm'
  get 'payments/retrieve', to: 'payments#retrieve'
  get 'payments/moneyback', to: 'payments#moneyback'
  resources :chat_rooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
   #these are handled by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def new
    @amount = Sale.new
    authorize @amount
  end

  def confirm
    @amount = Sale.new
    authorize @amount
    @amount = (params[:amount].to_f * 100).to_i
    if @amount < 0.5
      flash[:alert] = "Amount must be higher than 50 cents"
      redirect_to new_payment_path
    end
  end

  def create
    @amount = Sale.new
    authorize @amount
    @amount = (params[:amount].to_f * 100).to_i
    Stripe::Charge.create(
      source: params[:stripeToken],
      amount: @amount,
      currency: 'eur',
      description: 'Custom donation'
    )
    current_user.wallet += Money.new(@amount)
    current_user.save
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_payment_path
  end

  def retrieve
    @amount = Sale.new
    authorize @amount
  end

  def moneyback
    @amount = Sale.new
    authorize @amount
    @amount = (params[:amount].to_f * 100).to_i
    if current_user.wallet > Money.new(@amount)
      current_user.wallet -= Money.new(@amount)
      current_user.save!
    else
      flash[:alert] = "You don't have enough money"
      render :retrieve
    end
  end

end

app/views/payments/confirm.html.erb
<div class="container">
  <div class="row">
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-title'>
        <i class="fas fa-wallet"></i>
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-amount'>
        Balance:
        <%= current_user.wallet %> €
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class="col-sm-4 col-sm-offset-4">
      <div class = add-money>
        <div class="new-form">
          <div id="error_explanation">
        <h3> Adding to your Wallet  </h3>
      <%= form_tag payments_path(@sale, url: payments_path) do %>
        <article>
          <label class="amount">
            <span>Amount: <%= humanized_money_with_symbol(params[:amount]) %></span>
          </label>
        </article>
         <%= hidden_field_tag :amount, params[:amount] %>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-name="Adding Money to My Wallet"
            data-email="<%= current_user.email %>"
            data-description="Adding <%= params[:amount] %> € to your Wallet"
            data-amount="<%= params[:amount].to_f * 100 %> "
            data-currency="eur">
          </script>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/payments/create.html.erb
<div class="container">
  <div class="row">
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-title'>
        <i class="fas fa-wallet"></i>
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-amount'>
        Balance:
        <%= current_user.wallet %> €
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class="col-sm-4 col-sm-offset-4">
      <div class = add-money>
        <div class="new-form">
        <h2>Thank you!</h2>
        <p><strong><%= @amount * 0.01 %> €</strong> has been added to your wallet !</p>
        <div> <%= link_to "Back to shop", products_path, class: "button" %> </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/moneyback.html.erb
<div class="container">
  <div class="row">
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-title'>
        <i class="fas fa-wallet"></i>
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-amount'>
        Balance:
        <%= current_user.wallet %> €
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class="col-sm-4 col-sm-offset-4">
      <div class = add-money>
        <div class="new-form">
        <h2>Thank you!</h2>
        <p><strong><%= (params[:amount])%> €</strong> has been withdrawn from your wallet and will soon be arriving on IBAN: <%= (params[:card]) %></p>
        <%= link_to "Back to shop", products_path, class: "button" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/payments/new.html.erb
<div class="container">
  <div class="row">
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-title'>
        <i class="fas fa-wallet"></i>
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-amount'>
        Balance:
        <%= current_user.wallet %> €
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class="col-sm-4 col-sm-offset-4">
      <div class = add-money>
        <div class="new-form">
        <%= form_tag payments_confirm_path, method: 'get' do %>
          <div id="error_explanation">
            <% if flash[:error].present? %>
              <p><%= flash[:error] %></p>
            <% end %>
          </div>
          <article>
            <%= label_tag(:amount, 'Amount to add:') %>
            <%= text_field_tag(:amount) %>
          </article>
          <article>
            <%= hidden_field_tag(:stripeToken) %>
          </article>
          <button id='donateButton' class = 'button-add-money'>Add to Wallet</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/payments/retrieve.html.erb
<div class="container">
  <div class="row">
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-title'>
        <i class="fas fa-wallet"></i>
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class = 'col-sm-4 col-sm-offset-4'>
      <div class = 'wallet-amount'>
        Balance:
        <%= current_user.wallet %> €
      </div>
    </div>
  </div>

  <div class = 'row'>
    <div class="col-sm-4 col-sm-offset-4">
      <div class = add-money>
        <div class="new-form">
        <%= form_tag payments_moneyback_path, method: 'get' do %>
          <div id="error_explanation">
            <% if flash[:error].present? %>
              <p><%= flash[:error] %></p>
            <% end %>
          </div>
          <article>
            <%= label_tag(:amount, 'Amount to retrieve:') %>
            <%= text_field_tag(:amount) %>
          </article>
          <article>
            <%= label_tag(:card, 'Your Card Number') %>
            <%= text_field_tag(:card) %>
          </article>
          <button id='donateButton' class = button-add-money>Retrieve from Wallet</button>
        <% end %>
      </div>
    </div>
  </div>
</div>