config/routes.rb
Rails.application.routes.draw do

  get 'notifications/link_through'
  mount ActionCable.server => "/cable"
  get 'chat_rooms/show'
  get 'products/search', to: 'products#search'
  devise_for :users
  root to: 'products#index'
    resources :products do
      resources :pictures, only: [:new, :create, :destroy]
      resources :sales, only: [:create, :destroy] do
        resources :reviews, only: [:create, :new, :destroy]
      end
    end
  resources :users, except: [:destroy, :create, :new]
  get 'dashboard', to: 'users#dashboard'
  resources :payments, only: [:new, :create]
  get 'payments/confirm', to: 'payments#confirm'
  get 'payments/retrieve', to: 'payments#retrieve'
  get 'payments/moneyback', to: 'payments#moneyback'
  resources :chat_rooms, only: [:index, :create, :show] do
    resources :messages, only: [:create]
  end
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
   #these are handled by devise
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates_presence_of :name
  validates_presence_of :price
  validates_numericality_of :price, greater_than_or_equal_to: 0
  # validates_presence_of :picture
  validates_presence_of :pickup_time
  validate :date, on: :create
  validates_presence_of :pickup_address
  has_many :pictures, dependent: :delete_all
  has_many :notifications, dependent: :destroy
  has_one :sale
  monetize :price_cents
  geocoded_by :pickup_address
  after_validation :geocode, if: :will_save_change_to_pickup_address?

  def date
    if pickup_time < Time.now
      errors.add(:pickup_time, "should be in the future")
    end
  end

  def check_date
    if pickup_time < Time.now && status == "pending"
      self.status = "sold"
      self.save!
      create_notification_sold(self)
    elsif pickup_time < Time.now && status == "for-sale"
      self.status = "expired"
      self.save!
      create_notification(self)
    elsif pickup_time > Time.now && status == "expired"
      self.status = "for-sale"
      self.save!
    end
  end

  def category_icon
    case category
    when "Beauty and Wellbeing"
      "fas fa-lips"
    when "Books and Magazine"
      "fas fa-book-open"
    when "Movies and Video Games"
      "fas fa-film"
    when "High-Tech"
      "fas fa-tv"
    when "Toys and Youth"
      "fas fa-child"
    when "House and Pets"
      "fas fa-paw"
    when "Retail"
      "fas fa-shopping-cart"
    when "Clothing and Fashion"
      "fas fa-tshirt"
    when "Sport and Leisure"
      "fas fa-football-ball"
    when "Cars and Mechanics"
      "fas fa-car"
    when "Handmade"
      "fas fa-hand-holding-seedling"
    end
  end

  private

  def create_notification(product)
    Notification.create(user_id: product.user.id,
                          subscribed_user_id: product.user.id,
                          product_id: product.id,
                          notification_type: 'expired')
  end

  def create_notification_sold(product)
    Notification.create(user_id: product.sale.user.id,
                          subscribed_user_id: product.user.id,
                          product_id: product.id,
                          notification_type: 'finish')
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  helper_method :sort_direction

  def index
    if params[:km].present? && params[:category].present?
      @products = policy_scope(Product).joins(:user).where("products.category ilike ?", params[:category]).near(current_user.address, params[:km])
    elsif params[:km].present?
      @products = policy_scope(Product).near(current_user.address, params[:km])
    elsif params[:category].present?
      @products = policy_scope(Product).joins(:user).where("products.category ilike ?", params[:category])
    else
      @products = policy_scope(Product)
    end

    case params[:sort]
    when "Name"
      @products = @products.order("name ASC")
    when "Rating"
      @products = @products.sort_by { |product| product.user.average }.reverse!
    when "Distance"
      @products = @products.sort_by { |product| product.distance_from(current_user.address) }
    when "Price Ascending"
      @products = @products.order("price_cents ASC")
    when "Price Descending"
      @products = @products.order("price_cents DESC")
    end
  end

  def search
    @products = policy_scope(Product).joins(:user).where("products.name @@ ? OR products.description @@ ? OR users.first_name @@ ? OR users.last_name @@ ?", params[:query], params[:query], params[:query], params[:query])
    authorize @products
  end

  def show
    @chat_room = ChatRoom.new
    @picture = Picture.new
    unless @product.longitude.nil?
      @markers = [{
        lng: @product.longitude,
        lat: @product.latitude
      }]
    end
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    if @product.save
      flash[:notice] = "Product succesfully created"
      redirect_to new_product_picture_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      @product.check_date
      @product.save!
      flash[:notice] = "Product succesfully updated"
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to dashboard_path
  end


  private

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : 'asc'
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :pickup_time, :pickup_address, :category)
  end

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end
end

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :category, collection: [ "Books and Magazine", "Movies and Video Games", "High-Tech","Toys and Youth","House and Pets","Beauty and Wellbeing","Retail", "Clothing and Fashion", "Sport and Leisure", "Cars and Mechanics", "Handmade"].sort %>
    <%= f.label :pickup_time, 'Pickup Time' %>
    <div class='input-group date' id='datetimepicker'>
      <%= f.text_field :pickup_time, class: "form-control" %>
      <%= f.full_error :pickup_time, class: "alert alert-danger" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>

    <br>
    <%= f.input :pickup_address, input_html: {value: current_user.address} %>
    <%= f.button :submit, class: 'button' %>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="row form-add-product-margin">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form"  %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class = 'banner products'>
  <h1> Quick Sell </h1>
  <h3>
    <span id="banner-typed-text"></span>
  </h3>

  <div class='new-form'>
    <%= form_tag products_path(anchor: 'list'), method: :get do %>
      <% if user_signed_in? %>
        As far as <%= select_tag :km, options_for_select(["", "1", "5", "10", "15", "20", "50"])%> km in:
      <% end %>
      <%= select_tag :category, options_for_select([ "Books and Magazine", "Movies and Video Games", "High-Tech","Toys and Youth","House and Pets","Beauty and Wellbeing","Retail", "Clothing and Fashion", "Sport and Leisure", "Cars and Mechanics", "Handmade"].sort), include_blank: true%> <i class="fas fa-tags"></i> <br>
      <%= submit_tag "Find Your Happiness", class: "button-banner-search button-margin"%>
    <% end %>
  </div>
</div>

<hr/>

<div class = 'container'>
  <h3> Random Stuff </h3>
  Sort by :
  <%= form_tag products_path(anchor: 'list'), method: :get do %>
  <%= select_tag :sort, options_for_select(["Price Ascending", "Price Descending", "Name", "Rating", "Distance"].sort), include_blank: true%>
  <%= submit_tag "Sort"%>
  <% end %>
  <div class = 'row' id='list'>
    <% @products.each do |p| %>
      <% if p.status == "for-sale" %>
        <div class = 'col-sm-12 col-md-6'>
          <a href="/products/<%= p.id %>" style = "text-decoration: none">
            <div class= 'card-product'>
              <% if p.pictures.any? %>
                <div class = card-product-image style = "background-image: url(<%= cl_image_path(p.pictures.first.url, :width => 600, :crop => "pad") %>);">
                </div>
              <% else %>
                <div class = "card-product-image">
                  <div class = "card-icons" >
                    <i class = "<%= p.category_icon %>"> </i>
                  </div>
                </div>
              <% end %>

              <div class = 'card-product-description'>
                <% if user_signed_in? %>
                  <div class="card-product-distance">
                    <%=  p.distance_from(current_user.address) ? "#{p.distance_from(current_user.address).round(2)} km" : "" %>
                  </div>
                <% end %>
                <div class = 'card-product-description-name'> <%= p.name %> </div>
                <div class = 'card-product-description-price'> <%= p.price %> € </div>
              </div>
            </div>
          </a>
        </div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="row form-add-product-margin">
    <div class="col-md-6 col-md-offset-3">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<div class = 'banner products'>
  <h1> Results</h1>
</div>

<div class = 'container'>
  <div class = 'row' id='list'>
    <div class='col-md-8 col-md-offset-3'>
      <div class='new-form'>
      <%= form_tag products_path(anchor: 'list'), method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          placeholder: "Find a product",
          class: 'form-controle'
        %>
        <%= select_tag :category, options_for_select([ "Books and Magazine", "Movies and Video Games", "High-Tech","Toys and Youth","House and Pets","Beauty and Wellbeing","Retail", "Clothing and Fashion", "Sport and Leisure", "Cars and Mechanics", "Handmade"].sort), include_blank: true%>
        <%= submit_tag "Find Your Happiness", class: "btn btn-primary"%>
      <% end %>
      </div>
    </div>

    <% @products.each do |p| %>
      <% if p.status == "for-sale" %>
        <div class = 'col-sm-12 col-md-6'>
          <a href="/products/<%= p.id %>" style = "text-decoration: none">
            <div class= 'card-product'>
              <div class = card-product-image style = "background-image: url(<%= cl_image_path p.pictures.first.url if p.pictures.first %>);">

              </div>
              <div class = 'card-product-description'>
                <div class = 'card-product-description-name'> <%= p.name %> </div>
                <div class = 'card-product-description-price'> <%= p.price %> € </div>
              </div>
            </div>
          </a>
        </div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/products/show.html.erb
<% content_for :meta_title, "#{@product.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @product.description %>
<% content_for :meta_image, cl_image_path(@product.pictures) if @product.pictures.any? %>

<% if @product.pictures.any? %>
  <div class="container slideshow-container">
    <div class = 'row'>
      <% @product.pictures.each_with_index do |picture, index| %>
        <div class="mySlides" style = "background-image: url(<%= cl_image_path picture.url %>);">
          <div class="numbertext"> <%= index %> / <%= @product.pictures.size - 1 %> </div>
        </div>
      <% end %>

      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>

      <div class="caption-container">
        <% if @product.user == current_user %>
          <%= link_to "<i class='fas fa-plus-square'></i>".html_safe, new_product_picture_path(@product), class: "button-product-image" %>
        <% end %>
      </div>
    </div>

    <div class="row" style="display: flex; justify-content: flex-start;">
      <% @product.pictures.each_with_index do |picture, index| %>
        <div class="column cursor demo" style="background-image: url(<%= cl_image_path picture.url %>); width: 8%" onclick="currentSlide(<%= index+1%>)" alt="Picture">
          <% if picture.product.user == current_user %>
            <%= link_to "<i class='fas fa-trash-alt'></i>".html_safe, product_picture_path(@product, picture), class: "button-product-image", method: :delete, data: { confirm: "Are you sure? Picture won't appear anymore" }  %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <% if @product.user == current_user %>
    <div class="center">
      <%= link_to "Add a Picture".html_safe, new_product_picture_path(@product), class: "button" %>
    </div>
  <% end %>
<% end %>

<div class="container product-information">
  <div class="row">
    <div class="col-xs-12 col-sm-4">
      <div class = 'product-show-details'>
        <i class="fal fa-money-bill-alt fa-3x logo-product-detail"></i>
        <p><%= @product.price %> €</p>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class = 'product-show-details'>
        <button id="myBtn">
          <i class="fal fa-map-marker-alt fa-3x logo-product-detail"></i>
          <p><%= @product.pickup_address %></p>
        </button>
      </div>
    </div>
    <div class="col-xs-12 col-sm-4">
      <div class = 'product-show-details'>
        <i class="fal fa-clock fa-3x logo-product-detail"></i>
        <p><%= @product.pickup_time.strftime("%d/%m/%Y") %></p>
        <p><%= @product.pickup_time.strftime("%I:%M%p") %></p>
      </div>
    </div>

    <div class = 'row'>
      <div class = 'col-xs-12 col-sm-12 center'>
        <% if @product.status == "for-sale" && @product.user != current_user %>
          <%= form_tag product_sales_path(@product, @sales) do %>
            <%= hidden_field_tag 'product_id', @product.id, method: :post %>
            <%= submit_tag 'Purchase', class: 'button' %>
          <% end %>
        <% else %>
          <button class = 'button-alternative'>Purchase</button>
        <% end %>
      </div>
    </div>

    <% if @product.user == current_user %>
      <div class="row">
        <div class="col-sm-12">
          <div class = 'options-product-show'>
            <div>
              <%= link_to "Edit",edit_product_path(@product), class: 'button-banner-profile' %>
            </div>
            <div>
              <%= link_to "Delete", product_path(@product), class: 'button-banner-profile', method: :delete, data: { confirm: "Are you sure you want to delete this product?" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<hr/>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class = 'product-information'>
        <h2>Description</h2>
        <h5>Category:  <%= @product.category %> <i class = "<%= @product.category_icon %>"></i></h5>
        <%= @product.description %>
      </div>
    </div>
  </div>
</div>

<hr/>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <div class = 'product-information'>
        <div class="col-sm-3 col-sm-offset-1">
          <%= link_to cl_image_tag(@product.user.profile_picture, class: "profile-picture-avatar"), user_path(@product.user) %>
        </div>
        <div class="col-sm-7">
          <h4>Owner : <%= @product.user.first_name %>
          <%= @product.user.last_name %></h4>

          <p> <%= @product.user.profile_description %> </p>
          <% @product.user.average.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - @product.user.average).times do %>
            <i class="far fa-star"></i>
          <% end %>
          <% if user_signed_in? %>
            <%= form_for [@chat_room] do |f| %>
            <%= f.text_field :recipient_id, value: @product.user.id, type: "hidden" %>
            <%= f.text_field :sender_id, value: current_user.id, type: "hidden" %>
            <%= f.submit "Send Message", class: "button-small" %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>

  var slideIndex = 1;
  showSlides(slideIndex);

  // Next/previous controls
  function plusSlides(n) {
    showSlides(slideIndex += n);
  }

  // Thumbnail image controls
  function currentSlide(n) {
    showSlides(slideIndex = n);
  }

  function showSlides(n) {
    var i;
    var slides = document.getElementsByClassName("mySlides");
    var dots = document.getElementsByClassName("demo");
    var captionText = document.getElementById("caption");
    if (n > slides.length) {slideIndex = 1}
    if (n < 1) {slideIndex = slides.length}
    for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";
    }
    for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
    }
    slides[slideIndex-1].style.display = "block";
    dots[slideIndex-1].className += " active";
    captionText.innerHTML = dots[slideIndex-1].alt;
  }

</script>


<div id="myModal" class="modal">
  <div style="height: 400px; width: 400px; " class="modal-content">
    <span class="close">&times;</span>
  <div
    id="map"
    style="height: 400px;"
    data-marker="<%= @markers.to_json %>"
  ></div>
  </div>
</div>